//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace visitor_kiosk_asp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Registration
    {
        public int Id { get; set; }
        public short VisitReason { get; set; }
        public System.DateTime VisitDate { get; set; }
        public System.DateTime CheckInDate { get; set; }
    
        public virtual Visitor Visitor { get; set; }
    }
}
